"""initial migration

Revision ID: 57494e958963
Revises: 
Create Date: 2026-04-09 11:58:05.690312
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57494e958963'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Category display name'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL-friendly slug'),
    sa.Column('description', sa.Text(), nullable=True, comment='Category description'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (used for login)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Display username'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='User full name'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Contact phone number'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='Profile picture URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='User role: admin, owner, advertiser'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether email has been verified'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True, comment='Admin who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Action performed (e.g., 'user_deactivated', 'billboard_approved')"),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment="Entity type affected (e.g., 'user', 'billboard', 'booking')"),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='ID of the affected entity'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extra action details (before/after values, reason, etc.)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address of the admin (IPv4 or IPv6)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_action'), 'admin_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_logs_admin_id'), 'admin_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.create_table('billboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment="Billboard owner (user with 'owner' role)"),
    sa.Column('category_id', sa.UUID(), nullable=True, comment='Billboard category'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Billboard listing title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description'),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False, comment='Daily rental price'),
    sa.Column('price_per_week', sa.Numeric(precision=10, scale=2), nullable=True, comment='Weekly rental price (discount)'),
    sa.Column('price_per_month', sa.Numeric(precision=10, scale=2), nullable=True, comment='Monthly rental price (discount)'),
    sa.Column('address', sa.String(length=500), nullable=False, comment='Full street address'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='GPS latitude'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='GPS longitude'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City name for filtering'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='State/province for filtering'),
    sa.Column('size_type', sa.String(length=20), nullable=False, comment='Size: small, medium, large, digital'),
    sa.Column('is_illuminated', sa.Boolean(), nullable=False, comment='Whether the billboard has lighting'),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible specs: dimensions, material, traffic count, etc.'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: active, inactive, pending, rejected'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billboards_category_id'), 'billboards', ['category_id'], unique=False)
    op.create_index(op.f('ix_billboards_city'), 'billboards', ['city'], unique=False)
    op.create_index(op.f('ix_billboards_owner_id'), 'billboards', ['owner_id'], unique=False)
    op.create_index(op.f('ix_billboards_size_type'), 'billboards', ['size_type'], unique=False)
    op.create_index(op.f('ix_billboards_state'), 'billboards', ['state'], unique=False)
    op.create_index(op.f('ix_billboards_status'), 'billboards', ['status'], unique=False)
    op.create_index(op.f('ix_billboards_title'), 'billboards', ['title'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billboard_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Date for this analytics row'),
    sa.Column('views', sa.Integer(), nullable=False, comment='Number of detail page views'),
    sa.Column('inquiries', sa.Integer(), nullable=False, comment='Number of booking inquiries'),
    sa.Column('bookings_count', sa.Integer(), nullable=False, comment='Number of confirmed bookings'),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False, comment='Revenue from bookings on this date'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billboard_id'], ['billboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billboard_id', 'date', name='uq_billboard_date_analytics')
    )
    op.create_index(op.f('ix_analytics_billboard_id'), 'analytics', ['billboard_id'], unique=False)
    op.create_index(op.f('ix_analytics_date'), 'analytics', ['date'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who made the booking'),
    sa.Column('billboard_id', sa.UUID(), nullable=False, comment='Billboard being booked'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Booking start date (inclusive)'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Booking end date (inclusive)'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total booking price (locked at booking time)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending, confirmed, cancelled, completed'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes from the booker'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billboard_id'], ['billboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_billboard_id'), 'bookings', ['billboard_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('billboard_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billboard_id'], ['billboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'billboard_id', name='uq_user_billboard_favorite')
    )
    op.create_index(op.f('ix_favorites_billboard_id'), 'favorites', ['billboard_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billboard_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Path to original uploaded file'),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True, comment='Path to auto-generated thumbnail'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original upload filename'),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment='MIME type (e.g., image/jpeg)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Whether this is the main display image'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Controls image ordering in the gallery'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billboard_id'], ['billboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_billboard_id'), 'images', ['billboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_billboard_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_billboard_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_billboard_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_analytics_date'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_billboard_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_billboards_title'), table_name='billboards')
    op.drop_index(op.f('ix_billboards_status'), table_name='billboards')
    op.drop_index(op.f('ix_billboards_state'), table_name='billboards')
    op.drop_index(op.f('ix_billboards_size_type'), table_name='billboards')
    op.drop_index(op.f('ix_billboards_owner_id'), table_name='billboards')
    op.drop_index(op.f('ix_billboards_city'), table_name='billboards')
    op.drop_index(op.f('ix_billboards_category_id'), table_name='billboards')
    op.drop_table('billboards')
    op.drop_index(op.f('ix_admin_logs_created_at'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_admin_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_action'), table_name='admin_logs')
    op.drop_table('admin_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
