"""added invoices and owner booking flow

Revision ID: ac92853a8408
Revises: 57494e958963
Create Date: 2026-04-09 12:22:49.045848
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac92853a8408'
down_revision: Union[str, None] = '57494e958963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False, comment='The booking this invoice is for'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Owner who issued the invoice'),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='Client who needs to pay'),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='Unique reference number for the invoice'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total amount to be paid'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: unpaid, paid, overdue, cancelled'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or payment instructions'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_booking_id'), 'invoices', ['booking_id'], unique=True)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_owner_id'), 'invoices', ['owner_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_owner_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_booking_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
